#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "rspamd"
name = "Rspamd"

description.en = "Spam filtering system"
description.fr = "Système pour filtrer les spams"

version = "4.1.3~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://rspamd.com/"
admindoc = "https://rspamd.com/doc"
code = "https://github.com/rspamd/rspamd"

[integration]
yunohost = '>= 12.1.17'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]

    [resources.sources.trixie]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.3-1~f6297bc~trixie_amd64.deb"
    amd64.sha256 = "86e7721a7b29d60792d7e6f4f2298efa8530b7684f58a1fa76b0fd2fd6ef4d8f"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.3-1~f6297bc~trixie_arm64.deb"
    arm64.sha256 = "0d0d703139e50c4cea423b3325ffb91df56cceb5a5c628969d3374f4af11e23c"
    extract = false
    rename = "rspamd.deb"

    [resources.sources.bookworm]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.3-1~f6297bc~bookworm_amd64.deb"
    amd64.sha256 = "98b003b44a4acb5551e7f6188eb181909d9e914342789bf5e3964f0dbbd9abda"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.3-1~f6297bc~bookworm_arm64.deb"
    arm64.sha256 = "4f58ac83038d28734c9cf76379f26cd09eb5fb1aefe75a6f5418e3a281a04688"
    extract = false
    rename = "rspamd.deb"
    
    [resources.permissions]

    [resources.apt]
    packages = "redis-server, libhyperscan5, postfix, libsodium23, libsqlite3-0, libssl3, libarchive13, libbinutils"
