#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "rspamd"
name = "Rspamd"

description.en = "Spam filtering system"
description.fr = "Système pour filtrer les spams"

version = "4.1.2~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://rspamd.com/"
admindoc = "https://rspamd.com/doc"
code = "https://github.com/rspamd/rspamd"

[integration]
yunohost = '>= 12.1.17'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]

    [resources.sources.trixie]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.2-1~9fff684~trixie_amd64.deb"
    amd64.sha256 = "d8aa1e986e51f68b3cd4351b16a2f6736d85676fd94d187bf4dc4be06e8407cc"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.2-1~9fff684~trixie_arm64.deb"
    arm64.sha256 = "7afc3f46c0ee3912dff2a829a13891cd60dd1f19eeeccd8e2632ef112e6ceb98"
    extract = false
    rename = "rspamd.deb"

    [resources.sources.bookworm]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.2-1~9fff684~bookworm_amd64.deb"
    amd64.sha256 = "5875e8ffa93d62cc74506ff5f78d5bbbfcb467049230277a5f359537c96c8a04"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.1.2-1~9fff684~bookworm_arm64.deb"
    arm64.sha256 = "bd4161aba8e1fdee30635781929f160324b78034192e8905d1b0274a990d00c6"
    extract = false
    rename = "rspamd.deb"
    
    [resources.permissions]

    [resources.apt]
    packages = "redis-server, libhyperscan5, postfix, libsodium23, libsqlite3-0, libssl3, libarchive13, libbinutils"
