protocol imap {
  mail_plugins = imap_sieve
}

sieve_plugins = sieve_imapsieve sieve_extprograms
sieve_pipe_bin_dir = /usr/lib/dovecot/sieve-pipe

sieve_global_extensions {
  vnd.dovecot.pipe = yes
  vnd.dovecot.environment = yes
}

# Spam learning
mailbox Junk {
  sieve_script report-spam-junk {
    type = before
    cause = copy append
    path = /etc/dovecot/global_script/rspamd-report-spam.sieve
  }
}

# Ham learning
imapsieve_from Junk {
  sieve_script report-ham-junk {
    type = before
    cause = copy append
    path = /etc/dovecot/global_script/rspamd-report-ham.sieve
  }
}
