protocol imap {
  mail_plugins = $mail_plugins imap_sieve
}

sieve_plugins = sieve_imapsieve sieve_extprograms
sieve_pipe_bin_dir = /usr/lib/dovecot/sieve
sieve_global_extensions {
  vnd.dovecot.pipe = yes
  vnd.dovecot.environment = yes
}

# From elsewhere to Spam folder
mailbox Spam {
  sieve_script report-spam {
    type = before
    cause = copy
    path = /usr/lib/dovecot/sieve/report-spam.sieve
  }
}

# From Spam folder to elsewhere
imapsieve_from Spam {
  sieve_script report-ham-spam {
    type = before
    cause = copy
    path = /usr/lib/dovecot/sieve/report-ham.sieve
  }
}

# From elsewhere to Junk folder
mailbox Junk {
  sieve_script report-spam-junk {
    type = before
    cause = copy
    path = /usr/lib/dovecot/sieve/report-spam.sieve
  }
}

# From Junk folder to elsewhere
imapsieve_from Junk {
  sieve_script report-ham-junk {
    type = before
    cause = copy
    path = /usr/lib/dovecot/sieve/report-ham.sieve
  }
}
