#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"

ynh_backup "/etc/rspamd/local.d/redis.conf"
ynh_backup "/etc/rspamd/local.d/classifier-bayes.conf"

ynh_backup "/etc/dovecot/yunohost.d/post-ext.d/rspamd-learning.conf"
ynh_backup "/etc/dovecot/global_script/rspamd-spam-to-junk-folder.sieve"
ynh_backup "/etc/dovecot/global_script/rspamd-report-spam.sieve"
ynh_backup "/usr/lib/dovecot/sieve-pipe/rspamd-learn-spam.sh"
ynh_backup "/etc/dovecot/global_script/rspamd-report-ham.sieve"
ynh_backup "/usr/lib/dovecot/sieve-pipe/rspamd-learn-ham.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
