#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================

ynh_print_info --message="Declaring files to be backed up..."

ynh_backup --src_path="/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"
ynh_backup --src_path="/etc/dovecot/global_script/rspamd.sieve"
ynh_backup --src_path="/etc/dovecot/yunohost.d/post-ext.d/antispam.conf"

ynh_backup --src_path="/etc/rspamd"

ynh_backup --src_path="/etc/logrotate.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
