#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__per_user() {
    ynh_app_setting_get --app=$app --key=per_user
}

get__min_learns() {
    ynh_app_setting_get --app=$app --key=min_learns
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__per_user() {
    ynh_print_info "Saving the new per user classifier setting to $per_user in the Rspamd configuration..."
    ynh_app_setting_set --key=per_user --value=$per_user
    case "$per_user" in
        0) per_user_value="false" ;;
        1) per_user_value="true" ;;
    esac
    min_learns=$(ynh_app_setting_get --key=min_learns)
    ynh_config_add --template="rspamd_classifier-bayes.conf" --destination="/etc/rspamd/local.d/classifier-bayes.conf"
}

set__min_learns() {
    ynh_print_info "Saving the new minimum learn to count to perform classification to $min_learns in the Rspamd configuration..."
    ynh_app_setting_set --key=min_learns --value=$min_learns
    per_user=$(ynh_app_setting_get --key=per_user)
    case "$per_user" in
        0) per_user_value="false" ;;
        1) per_user_value="true" ;;
    esac
    ynh_config_add --template="rspamd_classifier-bayes.conf" --destination="/etc/rspamd/local.d/classifier-bayes.conf"
}

#=================================================
ynh_app_config_run "$1"
