#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__password() {
    echo ""
}

get__per_user() {
    ynh_app_setting_get --app=$app --key=per_user
}

get__min_learns() {
    ynh_app_setting_get --app=$app --key=min_learns
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__password() {
    if [ ! "$password" == "" ]
    then
        ynh_print_info --message="Saving the new password $password in the Rspamd configuration..."
        HASH=$(rspamadm pw -p "$password")
        echo "password = \"$HASH\"" > /etc/rspamd/local.d/worker-controller.inc
    fi
}

set__per_user() {
    ynh_print_info --message="Saving the new per user classifier setting to $per_user in the Rspamd configuration..."
    ynh_app_setting_set --key=per_user --value=$per_user
    ynh_config_add --template="rspamd_classifier-bayes.conf" --destination="/etc/rspamd/local.d/classifier-bayes.conf"
}

set__min_learns() {
    ynh_print_info --message="Saving the new minimum learn to count to perform classification to $min_learns in the Rspamd configuration..."
    ynh_app_setting_set --key=min_learns --value=$min_learns
    ynh_config_add --template="rspamd_classifier-bayes.conf" --destination="/etc/rspamd/local.d/classifier-bayes.conf"
}

#=================================================
ynh_app_config_run "$1"
