#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up $app..."

tmp_dir=$(mktemp -d)

ynh_setup_source --dest_dir="$tmp_dir"
dpkg -i $tmp_dir/rspamd.deb

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add --template="redis.conf" --destination="/etc/rspamd/local.d/redis.conf"
ynh_systemctl --service=rspamd --action="restart"

# Add postfix configuration hook and regen postfix conf
ynh_config_add --template="postfix_regenconf_hook" --destination="/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"
yunohost tools regen-conf postfix
ynh_systemctl --service=postfix --action="restart"

# Add dovecot conf
ynh_config_add --template="dovecot_sieve.conf" --destination="/etc/dovecot/global_script/rspamd.sieve"
sievec /etc/dovecot/global_script/rspamd.sieve
chown -R vmail:mail /etc/dovecot/global_script

ynh_config_add --template="dovecot_antispam.conf" --destination="/etc/dovecot/yunohost.d/post-ext.d/antispam.conf"
ynh_systemctl --service=dovecot --action="restart"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

# Integrate rspamd in YunoHost service list
yunohost service add $app --description="Spam filtering system"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
