#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

dpkg -r rspamd || true

# Remove postfix conf tweak
ynh_safe_rm /usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd
yunohost tools regen-conf postfix
ynh_systemctl --service=postfix --action="restart"

# Remove dovecot conf
ynh_safe_rm /etc/dovecot/global_script/rspamd.sieve
ynh_safe_rm /etc/dovecot/yunohost.d/post-ext.d/antispam.conf
ynh_systemctl --service=dovecot --action="restart"

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
