#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================

if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..."
	yunohost service remove $app
fi

ynh_script_progression --message="Removing $app sources..."

apt remove rspamd

ynh_script_progression --message="Removing system configurations related to $app..."

ynh_secure_remove /usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd
yunohost tools regen-conf postfix
ynh_systemd_action --service_name=postfix --action="restart"

ynh_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
