#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================

ynh_script_progression --message="Restoring system configurations related to $app..."

ynh_restore_file --src_path="/etc/rspamd"

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

# Integrate rspamd in YunoHost service list
yunohost service add $app --description="Spam filtering system"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
