#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"
yunohost tools regen-conf postfix
ynh_systemctl --service=postfix --action="restart"

ynh_restore "/etc/dovecot/global_script/rspamd.sieve"
ynh_restore "/etc/dovecot/yunohost.d/post-ext.d/antispam.conf"
sievec /etc/dovecot/global_script/rspamd.sieve
chown -R vmail:mail /etc/dovecot/global_script
ynh_systemctl --service=dovecot --action="restart"

ynh_restore "/etc/rspamd"

ynh_restore "/etc/logrotate.d/$app"

# Integrate rspamd in YunoHost service list
yunohost service add $app --description="Spam filtering system"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
