#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up rspamd..."

tmp_dir=$(mktemp -d) 
ynh_setup_source --dest_dir="$tmp_dir"
dpkg -i $tmp_dir/rspamd.deb

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..."

cp ../conf/redis.conf /etc/rspamd/local.d/redis.conf
ynh_systemd_action --service_name=rspamd --action="restart"

# Add postfix configuration hook and regen postfix conf
cp -R ../conf/postfix_regenconf_hook /usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd
yunohost tools regen-conf postfix
ynh_systemd_action --service_name=postfix --action="restart"

# Add dovecot conf
cp ../conf/dovecot_sieve.conf /etc/dovecot/global_script/rspamd.sieve
sievec /etc/dovecot/global_script/rspamd.sieve
chown -R vmail:mail /etc/dovecot/global_script
cp ../conf/dovecot_antispam.conf /etc/dovecot/yunohost.d/post-ext.d/antispam.conf
ynh_systemd_action --service_name=dovecot --action="restart"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

# Integrate rspamd in YunoHost service list
yunohost service add $app --description="Spam filtering system"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
