#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if ynh_app_upgrading_from_version_before 4.2.0~ynh1
then
    ynh_safe_rm "/etc/dovecot/global_script/rspamd.sieve"
    ynh_safe_rm "/etc/dovecot/yunohost.d/post-ext.d/antispam.conf"
    per_user=0
    ynh_app_setting_set --key=per_user --value=$per_user
    min_learns=200
    ynh_app_setting_set --key=min_learns --value=$min_learns
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up $app..."

tmp_dir=$(mktemp -d)

if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
    ynh_setup_source --dest_dir="$tmp_dir" --source_id="deb_bookworm"
elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
    ynh_setup_source --dest_dir="$tmp_dir" --source_id="deb_trixie"
fi

# Add the package to dependencies
YNH_APT_INSTALL_DEPENDENCIES_REPLACE="false" ynh_apt_install_dependencies "rspamd"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

# Add postfix configuration hook and regen postfix conf
ynh_config_add --template="yunohost_postfix_regenconf_hook" --destination="/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"
yunohost tools regen-conf postfix

# Add rspamd conf
## Add redis conf
ynh_config_add --template="rspamd_redis.conf" --destination="/etc/rspamd/local.d/redis.conf"

## Add per_user conf
per_user=$(ynh_app_setting_get --key=per_user)
case "$per_user" in
    0) per_user_value="false" ;;
    1) per_user_value="true" ;;
esac
ynh_config_add --template="rspamd_classifier-bayes.conf" --destination="/etc/rspamd/local.d/classifier-bayes.conf"

## Set permissions
chmod 644 /etc/rspamd/local.d/*

# Add dovecot conf
## Create sieve directories
mkdir -p /etc/dovecot/global_script
mkdir -p /usr/lib/dovecot/sieve-pipe

## Add the config file for spam handling
if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
    ynh_config_add --template="dovecot_rspamd-learning_bookworm.conf" --destination="/etc/dovecot/yunohost.d/post-ext.d/rspamd-learning.conf"
elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
    ynh_config_add --template="dovecot_rspamd-learning_trixie.conf" --destination="/etc/dovecot/yunohost.d/post-ext.d/rspamd-learning.conf"
fi

## Add the sieve script to move Spam mails to the user's Junk folder
ynh_config_add --template="dovecot_rspamd-spam-to-junk-folder.sieve" --destination="/etc/dovecot/global_script/rspamd-spam-to-junk-folder.sieve"

## Deploy imap_sieve scripts for spam/ham learning
### Spam learning
ynh_config_add --template="dovecot_rspamd-report-spam.sieve" --destination="/etc/dovecot/global_script/rspamd-report-spam.sieve"
ynh_config_add --template="dovecot_rspamd-learn-spam.sh" --destination="/usr/lib/dovecot/sieve-pipe/rspamd-learn-spam.sh"

### Ham learning
ynh_config_add --template="dovecot_rspamd-report-ham.sieve" --destination="/etc/dovecot/global_script/rspamd-report-ham.sieve"
ynh_config_add --template="dovecot_rspamd-learn-ham.sh" --destination="/usr/lib/dovecot/sieve-pipe/rspamd-learn-ham.sh"

## Set permissions
chmod 750 /etc/dovecot/global_script/*.sieve
chmod 755 /usr/lib/dovecot/sieve-pipe/rspamd-learn-*.sh

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

yunohost service add "$app" --description="Spam filtering system"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd services..."

ynh_systemctl --service=postfix --action=restart

ynh_systemctl --service=rspamd --action=restart

ynh_systemctl --service=dovecot --action=restart

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
